import { useState } from 'react'
import { Check, ExternalLink, Film, Plus, Star, Trash2, X } from 'lucide-react'
import type { PortfolioCategory, PortfolioProject } from '../types'

const categories: PortfolioCategory[] = ['bank projects','corporate videos','interviews','reels','color grading before/after','camera work','animation / titles']
const emptyProject: Omit<PortfolioProject,'id'> = { category:'bank projects', title:'', client:'', role:'Оператор-постановщик / колорист', work:'', link:'', strengths:'', improve:'', showreel:true }

export function PortfolioTracker({ projects, onAdd, onDelete }: { projects: PortfolioProject[]; onAdd: (project: Omit<PortfolioProject,'id'>) => void; onDelete: (id:string)=>void }) {
  const [filter,setFilter]=useState<PortfolioCategory | 'all'>('all')
  const [editing,setEditing]=useState(false)
  const [draft,setDraft]=useState(emptyProject)
  const filtered=filter==='all'?projects:projects.filter(project=>project.category===filter)
  const save=()=>{ if(!draft.title.trim()||!draft.client.trim()) return; onAdd(draft); setDraft(emptyProject); setEditing(false) }
  return <div className="space-y-4">
    <div className="grid gap-4 sm:grid-cols-3"><Metric value={String(projects.length)} label="проектов"/><Metric value={String(projects.filter(p=>p.showreel).length)} label="в шоурил"/><button onClick={()=>setEditing(true)} className="card flex items-center justify-center gap-2 bg-zinc-900 font-bold text-white dark:bg-white dark:text-zinc-900"><Plus/>Добавить проект</button></div>
    <div className="flex gap-2 overflow-x-auto pb-1"><button onClick={()=>setFilter('all')} className={`chip shrink-0 ${filter==='all'?'bg-zinc-900 text-white dark:bg-white dark:text-zinc-900':''}`}>Все</button>{categories.map(category=><button key={category} onClick={()=>setFilter(category)} className={`chip shrink-0 ${filter===category?'bg-zinc-900 text-white dark:bg-white dark:text-zinc-900':''}`}>{category}</button>)}</div>
    {editing&&<div className="card border-cobalt/40"><div className="mb-5 flex justify-between"><h2 className="text-xl font-bold">Новый проект</h2><button onClick={()=>setEditing(false)} className="icon-button"><X size={18}/></button></div><div className="grid gap-4 sm:grid-cols-2"><Select label="Раздел" value={draft.category} onChange={value=>setDraft({...draft,category:value as PortfolioCategory})}/><Input label="Название" value={draft.title} onChange={title=>setDraft({...draft,title})}/><Input label="Клиент" value={draft.client} onChange={client=>setDraft({...draft,client})}/><Input label="Роль пользователя" value={draft.role} onChange={role=>setDraft({...draft,role})}/><Area label="Что сделал" value={draft.work} onChange={work=>setDraft({...draft,work})}/><Input label="Ссылка" value={draft.link} onChange={link=>setDraft({...draft,link})}/><Area label="Сильные стороны" value={draft.strengths} onChange={strengths=>setDraft({...draft,strengths})}/><Area label="Что улучшить" value={draft.improve} onChange={improve=>setDraft({...draft,improve})}/></div><label className="mt-4 flex items-center gap-3 text-sm font-semibold"><input type="checkbox" checked={draft.showreel} onChange={event=>setDraft({...draft,showreel:event.target.checked})} className="h-5 w-5 accent-cobalt"/>Можно добавить в шоурил</label><button onClick={save} className="mt-5 w-full rounded-2xl bg-cobalt py-4 text-sm font-bold text-white">Сохранить проект</button></div>}
    {filtered.length===0?<div className="card py-14 text-center"><Film className="mx-auto text-zinc-300" size={40}/><h3 className="mt-4 font-bold">Пока нет проектов</h3><p className="mt-1 text-sm text-zinc-500">Добавь первый кейс — даже учебная работа считается.</p></div>:<div className="grid gap-4 lg:grid-cols-2">{filtered.map(project=><article className="card" key={project.id}><div className="flex items-start justify-between gap-3"><div><span className="text-[10px] font-bold uppercase tracking-wider text-cobalt">{project.category}</span><h3 className="mt-2 text-xl font-bold">{project.title}</h3><p className="mt-1 text-sm text-zinc-500">{project.client} · {project.role}</p></div><button onClick={()=>onDelete(project.id)} className="icon-button text-zinc-400 hover:text-red-500"><Trash2 size={16}/></button></div><p className="mt-5 text-sm leading-6">{project.work}</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><Note title="Сильные стороны" text={project.strengths}/><Note title="Что улучшить" text={project.improve}/></div><div className="mt-5 flex items-center justify-between border-t pt-4"><span className={`flex items-center gap-1.5 text-xs font-bold ${project.showreel?'text-amber-600':'text-zinc-400'}`}><Star size={15} fill={project.showreel?'currentColor':'none'}/>{project.showreel?'В шоурил':'Не в шоурил'}</span>{project.link&&<a href={project.link} target="_blank" rel="noreferrer" className="flex items-center gap-1 text-xs font-bold text-cobalt">Открыть <ExternalLink size={13}/></a>}</div></article>)}</div>}
  </div>
}

function Metric({value,label}:{value:string;label:string}){return <div className="card"><b className="text-3xl">{value}</b><p className="mt-1 text-xs font-bold uppercase tracking-wider text-zinc-400">{label}</p></div>}
function Input({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label><span className="label">{label}</span><input className="field" value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Area({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label><span className="label">{label}</span><textarea className="field min-h-24" value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Select({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label><span className="label">{label}</span><select className="field" value={value} onChange={e=>onChange(e.target.value)}>{categories.map(category=><option key={category}>{category}</option>)}</select></label>}
function Note({title,text}:{title:string;text:string}){return <div className="rounded-2xl bg-zinc-50 p-3 dark:bg-zinc-900"><p className="text-[10px] font-bold uppercase tracking-wider text-zinc-400">{title}</p><p className="mt-2 text-xs leading-5">{text||'—'}</p></div>}
